name: Build and Deploy Sphinx to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Sphinx (apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            python3-sphinx \
            python3-sphinx-rtd-theme \
            python3-myst-parser \
            python3-breathe \
            python3-exhale \
            make

      - name: Run doxygen
        run: |
          # Ensure Doxygen is installed
          sudo apt-get install -y doxygen graphviz

          # Run Doxygen to generate XML output
          doxygen Doxyfile

      - name: Build Sphinx HTML
        run: |
          # Use sphinx-build directly (doesn't depend on Poetry or pip)
          sphinx-build -b html docs docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
